server:
  port: ${PORT:8090}
  error:
    whitelabel:
      enabled: false

spring:
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
 
  driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  type-aliases-package: com.project.MyHome.domain.model
  mapper-locations: mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
